# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
 lane :adhoc do 
 match(
git_url: 'https://github.com/Sumit24796/Fastlane25April.git'
git_user_email: 'susingh@dminc.com'
type: 'adhoc'
)
end
end
